variables:
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: postgres

stages:
- test
- build

backend_test:
  stage: test
  image: rustlang/rust:nightly
  services:
  - postgres:latest
  script:
  - cd backend/
  - POSTGRES_PORT=5432 POSTGRES_HOST=$POSTGRES_HOST cargo test -j 1

build_backend:
  image: docker:20.10.17
  stage: build
  services:
  - docker:20.10.17-dind
  variables:
    IMAGE_TAG: "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG-$IMAGE_VERSION"
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $IMAGE_TAG ./backend
  - docker push $IMAGE_TAG
build_frontend:
  image: docker:20.10.17
  stage: build
  services:
  - docker:20.10.17-dind
  variables:
    IMAGE_TAG: "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG-$IMAGE_VERSION"
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $IMAGE_TAG ./frontend
  - docker push $IMAGE_TAG
