name: Build, test and push images

env:
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: postgres

on:
  push:
    branches:
      - main

jobs:
  backend_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Test backend
        working-directory: backend
        run: |
          POSTGRES_PORT=5432 POSTGRES_HOST=$POSTGRES_HOST cargo test -j 1

  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push backend image
        working-directory: backend
        env:
          IMAGE_TAG: ${{ secrets.DOCKER_REGISTRY }}/backend:${{ github.ref_slug }}-${{ github.run_number }}
        run: |
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push frontend image
        working-directory: frontend
        env:
          IMAGE_TAG: ${{ secrets.DOCKER_REGISTRY }}/frontend:${{ github.ref_slug }}-${{ github.run_number }}
        run: |
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
